### ISSUE TITLE
Documentation Nitpick: Reference to testing branch that doesn't exist

### ISSUE THREAD

**Issue by haxwithaxe** [geerlingguy/docker-debian12-ansible#6]
Just noticed this while making an Alpine version of your ansible images. This snipped in the ``README.md`` suggests there is a testing branch but there is none in this repo.
```
Note: Switch between master and testing depending on whether you want the extra testing tools present in the resulting image.
```
Thanks for making these images it's a real time saver!

**Comment by geerlingguy** [comment]
Thanks! Fixed it now :)
